import React, { useEffect } from "react";
import { api } from "../../services/api";
import { TableContainer } from "./_transactions";

export const Table = () => {
  // load server with transactions once the app is loaded
  useEffect(() => {
    api.get("transactions").then((response) => console.log(response.data));
  }, []);
  
  return (
    <TableContainer>
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Amount</th>
          <th scope="col">Category</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody>
        {/* tr td generated by maping a list */}
        <tr>
          <td>The Stranglers</td>
          <td>1974</td>
          <td>17</td>
          <td>
            No More Heroes <button>delete</button>
          </td>
        </tr>
      </tbody>
    </TableContainer>
  );
};
