import {  useContext } from "react";
import { numberFormat, dateFormat } from "../../helpers/formaters";
import { TableContainer } from "./_transactionsTable";
import { TransactionsContext } from "../../context/TransactionsContext";

export const TransactionsTable = () => {
  // calling context
  const {transactions} = useContext(TransactionsContext);

  return (
    <TableContainer>
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Amount</th>
          <th scope="col">Category</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody>
        {/* tr td generated by maping a list */}
        {transactions.map(({ id, title, amount, type, category, date }) => {
          return (
            <tr key={id}>
              <td>{title}</td>
              <td className={type}>{numberFormat(amount)}</td>
              <td>{category}</td>
              <td>{date}</td>
            </tr>
          );
        })}
      </tbody>
    </TableContainer>
  );
};
